//FULL GAME WIDTH

const GAME_WIDTH = 375;
const GAME_HEIGHT = 500;

//ENEMY HITBOX

const ENEMY_WIDTH = 75;
const ENEMY_HEIGHT = 156;
const MAX_ENEMIES = 1;

//PLAYER HITBOX

const PLAYER_WIDTH = 75;
const PLAYER_HEIGHT = 54;
